name: Deploy

on:
  repository_dispatch:
    types: [deploy-request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Get Environment
      run: echo ${{ github.event.client_payload.environment }}
    - name: Deploy Application
      run: echo "Deploying..."